# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0272736c751c555a6e050e4f4c1122c9dad562b0da87cd4764ff9385f2fd70ef4551f2bc49369f17841476b7d28217e23f4db39e851033ab479dac98c148b044

test:
  secret_key_base: 007056b51eeffaca17964ec2bb4107b2b85b754db277685b94e07d00572ee1921adbdd1c950a53dae02f5c9ab04bab94c91031a453ff638ac019a9f537cbe57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
